server:
  port: 8686
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sms_allocationDB?createDatabaseIfNotExist=true
#    username: user
#    password: password
    username: root
    password: root123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    dialect: org.hibeupdaternate.dialect.MySQL8Dialect
  application:
    name: allocation

security:
  oauth2:
    resource:
      token-info-uri: http://localhost:9192/oauth/check_token
    client:
      client-id: mobile
      client-secret: pin